/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoreIndexImport } from './routes/store/index'
import { Route as StoreProductIdImport } from './routes/store/$productId'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const DashboardUsersLazyImport = createFileRoute('/dashboard/users')()
const DashboardSuppliersLazyImport = createFileRoute('/dashboard/suppliers')()
const DashboardQsLazyImport = createFileRoute('/dashboard/qs')()
const DashboardOrdersLazyImport = createFileRoute('/dashboard/orders')()
const DashboardInventoryLazyImport = createFileRoute('/dashboard/inventory')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const StoreIndexRoute = StoreIndexImport.update({
  path: '/store/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersLazyRoute = DashboardUsersLazyImport.update({
  path: '/dashboard/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/users.lazy').then((d) => d.Route),
)

const DashboardSuppliersLazyRoute = DashboardSuppliersLazyImport.update({
  path: '/dashboard/suppliers',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/suppliers.lazy').then((d) => d.Route),
)

const DashboardQsLazyRoute = DashboardQsLazyImport.update({
  path: '/dashboard/qs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard/qs.lazy').then((d) => d.Route))

const DashboardOrdersLazyRoute = DashboardOrdersLazyImport.update({
  path: '/dashboard/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/orders.lazy').then((d) => d.Route),
)

const DashboardInventoryLazyRoute = DashboardInventoryLazyImport.update({
  path: '/dashboard/inventory',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/inventory.lazy').then((d) => d.Route),
)

const StoreProductIdRoute = StoreProductIdImport.update({
  path: '/store/$productId',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/store/$productId': {
      id: '/store/$productId'
      path: '/store/$productId'
      fullPath: '/store/$productId'
      preLoaderRoute: typeof StoreProductIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/dashboard/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/qs': {
      id: '/dashboard/qs'
      path: '/dashboard/qs'
      fullPath: '/dashboard/qs'
      preLoaderRoute: typeof DashboardQsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/suppliers': {
      id: '/dashboard/suppliers'
      path: '/dashboard/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof DashboardSuppliersLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersLazyImport
      parentRoute: typeof rootRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  StoreProductIdRoute,
  DashboardInventoryLazyRoute,
  DashboardOrdersLazyRoute,
  DashboardQsLazyRoute,
  DashboardSuppliersLazyRoute,
  DashboardUsersLazyRoute,
  StoreIndexRoute,
  DashboardIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth/login",
        "/auth/register",
        "/store/$productId",
        "/dashboard/inventory",
        "/dashboard/orders",
        "/dashboard/qs",
        "/dashboard/suppliers",
        "/dashboard/users",
        "/store/",
        "/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/store/$productId": {
      "filePath": "store/$productId.tsx"
    },
    "/dashboard/inventory": {
      "filePath": "dashboard/inventory.lazy.tsx"
    },
    "/dashboard/orders": {
      "filePath": "dashboard/orders.lazy.tsx"
    },
    "/dashboard/qs": {
      "filePath": "dashboard/qs.lazy.tsx"
    },
    "/dashboard/suppliers": {
      "filePath": "dashboard/suppliers.lazy.tsx"
    },
    "/dashboard/users": {
      "filePath": "dashboard/users.lazy.tsx"
    },
    "/store/": {
      "filePath": "store/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
